### PR TITLE
Wrong path when editing the .zshrc

### PR DESCRIPTION
**Pull request by primaulia**

### CODE REVIEW

**Comment by Eschults** [comment]
Hello @primaulia 👋 

Thank you for contributing 🙏 

The `windows.md` file is auto-generated by partials living in the [`_partials`](https://github.com/lewagon/setup/tree/master/_partials) folder, can you update your PR to only update partials (our Github Action will then [run the build](https://github.com/lewagon/setup/blob/master/.github/workflows/build.yml#L13) and commit the change in `windows.md` to your branch). 

❓ what makes you think the guidelines should refer to `~/.zshrc` and not `~/code/$GITHUB_USERNAME/dotfiles/zshrc`? The first one is only a symlink to the latter, the current solution should work unless I'm missing something 🤔? (cc @trandthanh?

**Comment by trandthanh** [comment]
Hi @primaulia & @Eschults 👋,

I actually added those lines because the students didn't know what to do when they reached that step. They didn't know how to get to their `zshrc` file or even understand that it was a file. 

I think that the mistake here is only the `.` on the last line right? It works on Macs but I think on Windows it should only be `code zshrc` instead of `code .zhsrc`? 🙏

**Comment by primaulia** [comment]
hey @trandthanh, sorry only manage to respond to this now 🙏 

But if you run `code zshrc`, are you editing the `zshrc` file in the dotfiles directory instead of the one on the root?

**Comment by trandthanh** [comment]
Hi @primaulia 👋,

As @Eschults mentioned, the one at the root is a symlink right 🤔? So going through the `dotfiles` should render the same results. I might be missing something but that's what I understood. Let me know!

**Comment by dmilon** [comment]
I've fixed the issue and explained why we can keep `code ~/.zshrc` in this PR https://github.com/lewagon/setup/pull/316.

**Pull request closed without merging**
