### PR TITLE
Add nvm to setup

### LINKED ISSUE #214: Add NVM to the setup
We need to add **nvm** to our setup in order to control the version of node installed by our students.
This will prevent errors like we had today on Rails D1 where [webpacker](https://github.com/rails/webpacker) does not support the last version of node.

Todo:
- [ ] Find the correct version of node we want to support 
- [ ] Add it to every setup

### PR DESCRIPTION
**Pull request by Eschults**
Fixes #214

I added the nvm / node setup guidelines for macOS after running a test on my machine with ruby 2.6.6 / rails 6.0.3.4 versions: webpacker seems to work fine with the LTS version of Node ([14.15.0](https://nodejs.org/en/)) 🎉 
Let's add guidelines for Linux and Windows too 🚀 
- @dmilon could you adapt the guidelines to Linux and run a quick test on your machine (after uninstalling your current versions of nvm / node)?
- @barangerbenjamin could you run a quick test on your WSL setup too?
No rush for this, let's do it by the end of the year to start with a fresh setup in 2021 👍 
Thank you 🙏

### CODE REVIEW

**Comment by dmilon** [comment]
@Eschults I added the Linux setup :heavy_check_mark:

**Comment by dmilon** [comment]
If we want `nvm` to have the same behavior than `rbenv`, that is to say to automatically switch the shell node version when we `cd` into a folder with a `.nvmrc` file, we need to add [these lines](https://github.com/lukechilds/zsh-nvm) to the [`zshrc` file in the dotfiles](https://github.com/lewagon/dotfiles/blob/master/zshrc). 

When preparing a PR on `karr` to update / remove `node` installation instructions, I stumbled on [this `oh-my-zsh` plugin](https://github.com/lewagon/karr/blame/master/lectures/rails/clever-cloud/hosting-deployment.md#L215) that could install `nvm` and update the `zshrc` file in order to source `.nvmrc` files automatically. That's seems worth looking into. I'll have a look and keep you posted.

**Comment by Eschults** [comment]
Thank you @dmilon 🙏 

@barangerbenjamin can you try following the Ubuntu instructions on your WSL and see if they work properly? If they do maybe @dmilon can duplicate them and add them to the Windows instructions 👌 ❔

**Comment by barangerbenjamin** [comment]
Hi, busy end of the year. I Will test now but any setup for Ubuntu should work for WSL 🙌

**Review by barangerbenjamin — APPROVED** [review]

**Review by barangerbenjamin — APPROVED** [review]

**Pull request merged**
