### PR TITLE
create shortcuts to the ubuntu file system in the windows file explorer

### PR DESCRIPTION
**Pull request by gmanchon**
we added this partial in the data-setup because it will allow students to easily exchange files between windows and ubuntu (csv files)

maybe it applies to the web setup as well for ressources ?

feel free to reject / update the content (did not find a better solution than a 2.7MB gif file for the video) 🙌

... thought about putting this in the wsl tricks section, but maybe it is a useful add on to the setup, WDYT ?

changes should be visible here https://github.com/lewagon/setup/blob/add-wsl-ubuntu-file-system-shortcut/WINDOWS.md#ubuntu-file-system

⚠️ I used a data-setup on a Windows VM in Parallels on a Mac. Maybe it is best to use a genuine Windows + web setup for the screenshot / video ?

### CODE REVIEW

**Comment by gmanchon** [comment]
if PR is accepted I'll propagate the change and use this partial in the data-setup...

**Comment by gmanchon** [comment]
cc @krokrob

**Comment by krokrob** [comment]
this can be useful to share images between Windows and Linux @juliends  please review

**Comment by barangerbenjamin** [comment]
Why not using `explorer.exe .` which is the equivalent to `open .` on  macOS?

**Comment by gmanchon** [comment]
Omg @barangerbenjamin, it works like a charm 🤦‍♂️ (I just had to `wsl --shutdown`).

@krokrob @juliends do we keep the partial and improve it with this solution ?

**Comment by krokrob** [comment]
Sure lets enrich it with `explorer.exe .`

**Pull request merged**
