### PR TITLE
Add instructions to update bundler

### PR DESCRIPTION
**Pull request by ajdubovoy**
Often students have to run these commands the first time they `bundle install`, so better to make them run it upfront probably.

resolve https://github.com/lewagon/fullstack-challenges/issues/2522

### CODE REVIEW

**Comment by Eschults** [comment]
👌

**Comment by ElvisDot** [comment]
The second command is bumping the bundler version in the Gemfile. Which is nice for rails projects. But in the current folder on setup day there is no Gemfile so it just fails with an error.

```
➜  /tmp bundle update --bundler
Could not locate Gemfile
```

**Comment by ajdubovoy** [comment]
Oh true you're absolutely right @ElvisDot will remove ASAP

**Comment by ajdubovoy** [comment]
Ok ^ that pr will remove 🚀

**Pull request merged**
