### PR TITLE
Fix typos and translations of Windows and Ubuntu pt-br partials

### PR DESCRIPTION
**Pull request by gbs0**
Fixed some emojis, misspellings and translations of Portuguese Windows setup instructions

### CODE REVIEW

**Comment by Eschults** [comment]
👋 @gbs0 thank you for contributing 🙏 

Changes must be done in partial files at https://github.com/lewagon/setup/tree/master/_partials/pt otherwise the next [build](https://github.com/lewagon/setup/blob/master/build.rb) will erase all the changes hardcoded in `windows.pt.md` 👌

**Comment by gbs0** [comment]
@Eschults @carlosferrerdev All files are now updated, can you guys review my PR?

**Comment by carlosferrerdev** [comment]
Its good to go! Thanks for that @gbs0.

**Comment by gbs0** [comment]
Waiting maintainers approval

**Comment by gbs0** [comment]
@Eschults Can you merge this PR for our new batches?

**Pull request merged**
