### PR TITLE
Split code blocks into one-liners

### PR DESCRIPTION
**Pull request by mdik**
Experience shows that students copypaste as many lines as there are per code block. This leads to errors down the road because usually only one of the lines gets executed.

This PR fixes that by typesetting the lines each on its own.

### CODE REVIEW

**Comment by dmilon** [comment]
Hi @mdik :wave: Thank you for your contribution :pray: 

Actually, the code lines which are grouped together in the same code block can be executed together. If students copy select all of them and then copy them (or better click on the copy button) and then paste them in their terminal, they will be executed one after the other :point_down: 

instructions

Splitting the code blocks so that each one as a single line would make copy-pasting the instructions more tedious and would increase the risk for a student to miss a code line.

**Comment by mdik** [comment]
> Hi @mdik wave Thank you for your contribution pray
> 
> Actually, the code lines which are grouped together in the same code block can be executed together. If students copy select all of them and then copy them (or better click on the copy button) and then paste them in their terminal, they will be executed one after the other point_down

My experience is very different. It is exactly the code blocks that are _not_ formatted into single lines that fail all the time when students copypaste. Plus, either way, even if it does work as it does for you, students won't notice if any of the commands before the last throw errors.

Formatting code-blocks into separate lines was agreed upon several years ago for those reasons, and I would like to keep it that way!

**Comment by v-natalia** [comment]
Hi @dmilon. This week I had +12 people having issues with these two lines running together

```
sudo apt update
sudo apt install -y curl git imagemagick jq unzip vim zsh
```
Also, the `code --install `section was also problematic this time. I had to re-do many times the lines separate....

**Comment by mdik** [comment]
Same for me as well, so it's safe to assume that this happened with all ca. 50 students, which means we spent about 50·5 minutes = 4 person-hours on mitigating something that was potentially fixed 3 months ago :woman_shrugging:

**Comment by dmilon** [comment]
Hi all :wave: 

Thank you for your feedback :pray: 

Can you elaborate on the error your students get? What is the error message displayed when a command fails to run? Are they running macOS, Windows or Linux? 

I would like to understand the bug they are having before jumping into a fix which would deeply impact all our students setup experience.

**Comment by mdik** [comment]
Yes, sure, to quote myself from 18 days ago: "Plus, either way, even if it does work as it does for you, students won't notice if any of the commands before the last throw errors.".

In practice this means, that the commands requiring `jq` or `zsh` a few paragraphs after the ones Natalia mentioned, fail, i.e.

```bash
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```

and/or

```bash
export GITHUB_USERNAME=`gh api user | jq -r '.login'`
echo $GITHUB_USERNAME
```

**Comment by mdik** [comment]
Please also note
https://github.com/lewagon/setup/issues/149
and
https://github.com/lewagon/setup/pull/154

**Comment by mdik** [comment]
Hello.

We found a few more things, we like to update in the guides, but before we do that I wanted to ask, if it would be even worth our time, as there are no answers to our request here?

Please advice.

**Comment by Eschults** [comment]
Thank you @mdik for the PR 🙏 ! 
❓ @krokrob any impact to reflect on https://github.com/lewagon/data-setup?

**Comment by krokrob** [comment]
@Eschults sure, we need to regenerate the instructions

**Pull request merged**
