### PR TITLE
Rename WINDOWS.md to WINDOWS_2.md

### PR DESCRIPTION
**Pull request by yadoyadoya**
This is a way for students to do be able to do everything while staying in Windows

I don't know whether they still have to install sublime from bash, so I left the original instructions there as it doesn't hurt.

Took me weeks of research, but normally they should be able to do all the bootcamp the same way as everyone by following these instructions :)

Please please accept it :)

### CODE REVIEW

**Comment by alex-felix** [comment]
it’s time to seriously look at this imo

**Comment by alex-felix** [comment]
Thanks for the PR

**Comment by alex-felix** [comment]
imo this is has to be one version - not sure it will be merged tomorrow though 😉

**Comment by ssaunier** [comment]
Interesting, thanks for the work! We'll investigate that in the inter-batch period in Paris.

Cheers 🎉 !

**Comment by ssaunier** [comment]
Thanks for your research 🙏 

We now have an official dedicated [WLS setup](https://github.com/lewagon/setup/blob/master/WINDOWS_LINUX_SUBSYSTEM.md)

**Pull request closed without merging**
