### PR TITLE
Add mic and cam test

### PR DESCRIPTION
**Pull request by dmilon**
@barangerbenjamin : I was asked by @ssaunier to add these checks in the setup. 

BTW, I've noticed that two files of the WLS are prefixed with `wsl` and not `wls`. Is it normal or a typo? I just wanted to bring it up.

### CODE REVIEW

**Comment by ssaunier** [comment]
LGTM! @barangerbenjamin I'll let you merge this and handle potential conflict with your current branch (as you are moving this section up). Thanks!

**Comment by barangerbenjamin** [comment]
Hey @dmilon
No worries, I will merge yours in my current PR.
I'm currently re-writing the whole WSL section, you should use `wsl` as it is the correct acronym for `Windows Subsystem for Linux`, `wls` is a typo from before that persisted somehow 😂

**Comment by barangerbenjamin** [comment]
LGTM, but it says to ask a teacher if it ain't green, and mine is red just because I don't have a webcam 
Capture

**Comment by barangerbenjamin** [comment]
Shall we say that it is expected to be green for all the peripherals that the student has (microphone & webcam)

**Comment by dmilon** [comment]
@barangerbenjamin : I didn't know the correct acronym was WSL. I always say WLS. Thanks! 

For your all green microphone and camera comment, I think we can keep it this way so that the teacher is noticed that this particular student doesn't have a camera and the teaching staff will not be suprised if we don't see his video during Zoom calls.

**Comment by barangerbenjamin** [comment]
Sounds good to me 👍

**Pull request merged**
