### PR TITLE
[Important PR~not to merge without deployment plan] Upgrade to Ruby 3.3.5

### PR DESCRIPTION
**Pull request by ajdubovoy**
OK, I can't believe this is finally finished. I went through every web-dev or assess repo and upgrading the Ruby version and standardized the Rails and Puma versions.

cc @Eschults @mathildetestard 

Here was basically my process:

1. Go through every single repo (most of which are solutions/examples) and upgrade the relevant versions.
2. Set up the DB and run server.
3. Click around and make sure it seems like all the core features are working.

I didn't find that many huge bugs, but without automated testing on most of these, it's a bit hard for me to say there aren't any with 100% certainty.

Then I went to `fullstack-solutions` and did a version update there and ran `rake_all` to check for any broken rake tests in any challenges.

Finally, I went to `fullstack-challenges` and added a `.ruby-version` file (there wasn't already one there).

The only thing I wonder if it could slip through the cracks right now is maybe if there's a challenge where there's no `rake` but something weird and technical broke....it's entirely possible but a bit hard for me to predict in advance.

Sooooo many repos affected.

Related PRs:

- https://github.com/lewagon-assess/rails-book-rooms-challenge/pull/13
- https://github.com/lewagon-assess/rails-share-posts-challenge/pull/13
- https://github.com/lewagon-assess/rails-rent-cars-challenge/pull/16
- https://github.com/lewagon-assess/rails-garden-manager/pull/8
- https://github.com/lewagon/active-record-boilerplate/pull/17
- https://github.com/lewagon/activerecord-sinatra-boilerplate/pull/17
- https://github.com/lewagon/bookstore/pull/13
- https://github.com/lewagon/fullstack-meta/pull/440
- https://github.com/lewagon/gardens-and-plants/pull/31
- https://github.com/lewagon/gardens-and-plants/pull/32
- https://github.com/lewagon/gardens-and-plants/pull/33
- https://github.com/lewagon/hosting-image-upload/pull/2
- https://github.com/lewagon/lost-kitty/pull/39
- https://github.com/lewagon/rails-action-cable-chat/pull/25
- https://github.com/lewagon/rails-address-book/pull/1
- https://github.com/lewagon/rails-authentication/pull/3
- https://github.com/lewagon/rails-authorization/pull/20
- https://github.com/lewagon/rails-background-jobs/pull/5
- https://github.com/lewagon/rails-beyond-crud/pull/1
- https://github.com/lewagon/rails-crud/pull/3
- https://github.com/lewagon/rails-db-advanced/pull/18
- https://github.com/lewagon/rails-db-advanced/pull/19
- https://github.com/lewagon/rails-etsy/pull/2
- https://github.com/lewagon/rails-geocoding/pull/7
- https://github.com/lewagon/rails-intro/pull/1
- https://github.com/lewagon/rails-longest-word-game/pull/1
- https://github.com/lewagon/rails-pokemon/pull/2
- https://github.com/lewagon/rails-products-ai/pull/3
- https://github.com/lewagon/rails-recipes-ai/pull/8
- https://github.com/lewagon/rails-search/pull/2
- https://github.com/lewagon/rails-simple-airbnb/pull/30
- https://github.com/lewagon/rails-static-airbnb/pull/1
- https://github.com/lewagon/rails-static-airbnb/pull/2
- https://github.com/lewagon/rails-stupid-coaching/pull/1
- https://github.com/lewagon/rails-task-manager/pull/2
- https://github.com/lewagon/rails-watch-list/pull/28
- https://github.com/lewagon/rails-watch-list/pull/29
- https://github.com/lewagon/rails-wikinimous/pull/2
- https://github.com/lewagon/rails-yelp-mvp/pull/4
- https://github.com/lewagon/teddies-shop/pull/1
- https://github.com/lewagon/fullstack-solutions/pull/321
- https://github.com/lewagon/fullstack-challenges/pull/2715

### CODE REVIEW

**Comment by ajdubovoy** [comment]
I'm also not really sure what the best deployment approach is here. It's sooooo many repos that I'd really like to avoid having to do some kind of a beta branch in an ideal world

**Comment by mathildetestard** [comment]
Huge work, thanks @ajdubovoy 👏 

Hi @Eschults & @pmochkovitch 👋 
What are you reco regarding deploying this change?
- Edward you mentioned in [this issue](https://github.com/lewagon/help/issues/6641#issuecomment-2358764043) there's still a batch going on, would you recommend to wait for Sept 28? 
- do you think we can proceed without using a beta branch to save Alex some time or this is a necessary step of the process?

Thanks 🙏

**Comment by Eschults** [comment]
No need for a beta branch indeed, I recommend:
1. merging the AI evolution on Sept 28th
2. switching batches from the AI program to the master program
3. pulling a `no-update` branch from `master` for running batches (we don't want students to change versions in the middle of their batches)
4. switching running batches to `no-update`
5. merging this in `master` for upcoming batches 👌 

You will need help from Engineering for steps 2 and 4, feel free to ping me 👍

**Comment by ajdubovoy** [comment]
OK! Wow, making a `no-update` branch for this will end up being a lot of fishing, because we'll also have to move links to all the related repos to `no-update`. Unless we're OK with most of the Rails solution repos being on the new Ruby version even for batches where students' computers aren't on that version yet

**Comment by Eschults** [comment]
Hmm let's limit the `no-update` branches to repos students are expected to clone / run `rails s` with. Teachers should be able to switch versions and I don't foresee any impacts on the corresponding demos / livecodes 🤔

**Comment by ajdubovoy** [comment]
Hi @Eschults reposting from Slack

**Comment by ajdubovoy** [comment]
On lewagon/flashcards, just in case, I just made a `no-update-ruby-3.3.5` branch so we have something

**Comment by Eschults** [comment]
Thank you @ajdubovoy for creating the branches 🙌 I just ran 👇 to switch running web batches to the [Web Development without update](https://kitt.lewagon.com/programs/web_no_update/challenge) program 👌 

```ruby
> Camp.running.where(program_id: 1).update_all(program_id: 52)
=> 14
> p = Program.find(52)
> p.update_shas
=> true
```

Merging PRs now 👍

**Comment by Eschults** [comment]
✅ Done. There are a handful of PRs w/ conflicts, I assigned them to you, feel free to self-merge when solved 👍

**Comment by ajdubovoy** [comment]
Thank you!

**Pull request merged**
