### PR TITLE
Update yarn installation instructions

### PR DESCRIPTION
**Pull request by ajdubovoy**
resolve https://github.com/lewagon/setup/issues/464

### CODE REVIEW

**Comment by ajdubovoy** [comment]
@Eschults implemented the recommendation in https://github.com/lewagon/setup/issues/464.

But, I don't really have a good way of testing it. I did find `corepack` is installed on my system already, so this bodes well.

@ElvisDot do you maybe have a burner system you could test this on hahah? No worries if no!

I could also always try setting up a DigitalOcean droplet for a day and see if I can run our setup via SSH on Ubuntu, I guess.......

**Review by Eschults — APPROVED** [review]
LGTM++ 

Sorry Engineering's bandwidth is the same as in https://github.com/lewagon/setup/issues/464#issuecomment-2056554544 😕

**Comment by ajdubovoy** [comment]
No worries! But do we feel comfortable merging this without having at least tested it on Windows once?

**Comment by Eschults** [comment]
Let's ask in #teachers if someone is on Windows and would be so kind to run the two commands for us 😇

**Comment by ajdubovoy** [comment]
Ok will do!

**Comment by ajdubovoy** [comment]
https://lewagon-alumni.slack.com/archives/G02NFDT0J/p1716393474945849

**Comment by ajdubovoy** [comment]
Hmmm so apparently it doesn't work with our node version on Ubuntu.

https://lewagon-alumni.slack.com/archives/G02NFDT0J/p1716555678386209?thread_ts=1716393474.945849&channel=G02NFDT0J&message_ts=1716555678.386209

I guess should we table merging this until we upgrade mode?

**Comment by ajdubovoy** [comment]
It also seems like the issue on Natalia's computer was actually some kind of network error we haven't been able to solve yet. I do wonder if the same thing might happen to students, but it's also not necessarily a reason not to merge this

**Comment by ajdubovoy** [comment]
I also think we don't use yarn at any point in the bootcamp anymore, so it wouldn't be a breaking problem if it didn't install on somebody's laptop

**Comment by Eschults** [comment]
👍

**Pull request merged**
